application: contextphone-1253
version: 1
runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: main.php

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico











