application: contextphone-v1
version: 1
runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /getdata.php*
  script: getdata.php


- url: /.*
  script: main.php

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico











